spring.application.name=Personal-Finance-Tracker
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.session.cookie.same-site=strict

logging.file.name=logs/application.log
logging.level.root=INFO
logging.logback.rollingpolicy.max-file-size=5MB